//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student1
    {
        public int id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public System.DateTime dob { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public long pin { get; set; }
        public double ssc { get; set; }
        public decimal mob_no { get; set; }
        public int cno { get; set; }
        public int rid { get; set; }
    
        public virtual course course { get; set; }
        public virtual registration registration { get; set; }
    }
}
